### ISSUE TITLE
Import disk by id, not by kernel-generated name

### ISSUE THREAD

**Issue by seletskiy** [demizer/archzfs#35]
I've took a glance look at code and found, that current mkinitcpio hook implementation always import pool by using devices, located at `/dev` (from man page on `zpool`).

This approach can cause troubles when having pool consisting of large number of disks.

Today, we ended up with unbootable server in spite of pool was created by specifying names from `/dev/disk/by-id`. `zpool import` in emergency console shows broken pool which consist of disks named `sda`, `sdb` and so on.

Problem was fixed by:

* booting from livecd;
* re-importing pool by command  
  `zpool import -R /mnt -d /dev/disk/by-id zroot`
* rebuilding initramfs with  
  `mkinitcpio -p linux`

Maybe, hook should support some option to manually change import lookup dir (e.g. by passing `-d ...` option to the zpool import command).

What do you think? I can prepare PR.

**Comment by demizer** [comment]
This is no bueno. Please submit a PR when you can. Thank you!

**Comment by bjin** [comment]
Did I missed something or is this already been addressed by #29 and #30

**Comment by seletskiy** [comment]
Oh, sorry! My bad. Didn't look carefully. It's already implemented.

Thanks!
